config/routes.rb
Bigdata::Application.routes.draw do
  resources :tweets_weights

  resources :suggested_keywords
    
  get "getstarted/twitter"

  get "getstarted/topic"

  get "getstarted/welcome"
  
  get "getstartedtwitter/new"
  get "getstartedtwitter/callback"
  resources :friends_withs

  resources :rss_sources

  resources :comments

  resources :twitter_accounts

  get "analytics/index"

  get "settings/index"

  post "twitter_accounts/new"
  get "twitter_accounts/new"
  resources :search_bins
  get "search_bins/new"

  get "search_bins/create"

  post "search_bins/new"

resource :twitter_account
  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback

  resources :users

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  post "sessions/new"
    
    post "sessions/create"

  get "admin/index"

  get "twitter_manager/post"
   
  resources :l_tweets

  get "reader/index"
  post "reader/update_news"
  get  "reader/update_news"
  get "reader/setting"

  get "reader/analytics"

  resources :landing_page	
	
  get "landing_page/index"
	
  resources :visitors
  
  get 'admin' => 'reader#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "aboutus/about"
  get "register/reg"
  get "home/index"
  get "home/register"
  get "home/about"
  resources :cohorts
  resources :prospective_users
  get "prospective_users/new"

  root :to => 'landing_page#index'

end

app/models/rss_source.rb
class RssSource < ActiveRecord::Base
  belongs_to :user
  validates :source_url, :presence => true
end

app/controllers/rss_sources_controller.rb
class RssSourcesController < ApplicationController
  # GET /rss_sources
  # GET /rss_sources.json
  def index
    @rss_sources = current_user.rss_sources.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rss_sources }
    end
  end

  # GET /rss_sources/1
  # GET /rss_sources/1.json
  def show
    @rss_source = RssSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @rss_source }
    end
  end

  # GET /rss_sources/new
  # GET /rss_sources/new.json
  def new
    @rss_source = RssSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @rss_source }
    end
  end

  # GET /rss_sources/1/edit
  def edit
    @rss_source = RssSource.find(params[:id])
  end

  # POST /rss_sources
  # POST /rss_sources.json
  def create
    @rss_source = RssSource.new(params[:rss_source])
    @rss_source.user_id = current_user.id;
    respond_to do |format|
      if @rss_source.save
        format.html { redirect_to @rss_source, :notice => 'Rss source was successfully created.' }
        format.json { render :json => @rss_source, :status => :created, :location => @rss_source }
      else
        format.html { render :action => "new" }
        format.json { render :json => @rss_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rss_sources/1
  # PUT /rss_sources/1.json
  def update
    @rss_source = RssSource.find(params[:id])

    respond_to do |format|
      if @rss_source.update_attributes(params[:rss_source])
        format.html { redirect_to @rss_source, :notice => 'Rss source was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @rss_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_sources/1
  # DELETE /rss_sources/1.json
  def destroy
    @rss_source = RssSource.find(params[:id])
    @rss_source.destroy

    respond_to do |format|
      format.html { redirect_to rss_sources_url }
      format.json { head :ok }
    end
  end
end

app/helpers/rss_sources_helper.rb
module RssSourcesHelper
end

app/views/rss_sources/_form.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8' />
	<title>Seedr</title>
	<meta content='width=device-width, initial-scale=1.0' name='viewport' />
	<meta content='' name='description' />
	<meta content='' name='author' />
	
	<link rel="stylesheet" type="text/css" href="/stylesheets/bootstrap.css" />	<link rel="stylesheet" type="text/css" href="/stylesheets/home.css" />	</head>
	<link rel="stylesheet" href="/stylesheets/basic.css" type="text/css">
   	<script type='text/javascript' src='/js/jquery.js'></script>
	<script type='text/javascript' src='/js/jquery-1.7.2.min.js'></script>
	<body>
		<div class="container">
			<div id="header" class="span12">
				<h1>Seedr</h1>
			</div>
			<div class="span12">
				<%= form_for(@rss_source) do |f| %>
  					<% if @rss_source.errors.any? %>
    				<div id="error_explanation">
      					<h2><%= pluralize(@rss_source.errors.count, "error") %> prohibited this rss_source from being saved:</h2>

      					<ul>
      					<% @rss_source.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      					<% end %>
      					</ul>
   					</div>
  				<% end %>
				<div class="field">
					<%= f.label :source_url, 'RSS Source URL: ' %>
				    <%= f.text_field :source_url %><br />
				</div>
				<div class="span10 offset2">
					<%= f.submit "Create Source", :class=>'btn btn-info' %>
				</div>
				<% end %>				
			</div>
			<div class='span12' id='footer' style="margin-top: 120px">
				<div class='row'>
					<div class='span3'>
						<ul class="nav nav-pills">
							<div>
							<a href="https://twitter.com/SeedrSocial" class="twitter-follow-button" data-show-count="false">Follow @SeedrSocial</a>
							</div>	
							<div class="fb-like" data-href="http://www.facebook.com/SeedrSocial" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
												
						</ul>
					</div>
					<div class='span8' id='copyright'><p>Contact us at contact@seedrsocial.com | &copy;2012 Seedr. All rights reserved.</p></div>
				</div>
			</div>
		</div> <!--container!-->
		<div id="fb-root"></div>
		
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=386595491374845";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<!-- <script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script> -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script></body>
</html>

app/views/rss_sources/edit.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8' />
	<title>Seedr</title>
	<meta content='width=device-width, initial-scale=1.0' name='viewport' />
	<meta content='' name='description' />
	<meta content='' name='author' />
	
	<link rel="stylesheet" type="text/css" href="/stylesheets/bootstrap.css" />	<link rel="stylesheet" type="text/css" href="/stylesheets/home.css" />	</head>
	<link rel="stylesheet" href="/stylesheets/basic.css" type="text/css">
   	<script type='text/javascript' src='/js/jquery.js'></script>
	<script type='text/javascript' src='/js/jquery-1.7.2.min.js'></script>
	<body>
		<div class="container">
			<div id="header" class="span12">
				<h1>Seedr</h1>
			</div>
			<div class="span12">
				<h3>Editing RSS source</h3> <br />
				<%= form_for(@rss_source) do |f| %>
  					<% if @rss_source.errors.any? %>
    				<div id="error_explanation">
      					<h2><%= pluralize(@rss_source.errors.count, "error") %> prohibited this rss_source from being saved:</h2>

      					<ul>
      					<% @rss_source.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      					<% end %>
      					</ul>
   					</div>
  				<% end %>
				<div class="field">
					<%= f.label :source_url, 'RSS Source URL: ' %>
				    <%= f.text_field :source_url %><br />
				</div>
				<div class="span10 offset2">
					<%= f.submit "Create Source", :class=>'btn btn-info' %>
				</div>
				<% end %>				
			</div>
			<div class='span12' id='footer' style="margin-top: 120px">
				<div class='row'>
					<div class='span3'>
						<ul class="nav nav-pills">
							<div>
							<a href="https://twitter.com/SeedrSocial" class="twitter-follow-button" data-show-count="false">Follow @SeedrSocial</a>
							</div>	
							<div class="fb-like" data-href="http://www.facebook.com/SeedrSocial" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
												
						</ul>
					</div>
					<div class='span8' id='copyright'><p>Contact us at contact@seedrsocial.com | &copy;2012 Seedr. All rights reserved.</p></div>
				</div>
			</div>
		</div> <!--container!-->
		<div id="fb-root"></div>
		
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=386595491374845";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<!-- <script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script> -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script></body>
</html>

app/views/rss_sources/index.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8' />
	<title>Seedr</title>
	<meta content='width=device-width, initial-scale=1.0' name='viewport' />
	<meta content='' name='description' />
	<meta content='' name='author' />
	
	<link rel="stylesheet" type="text/css" href="/stylesheets/bootstrap.css" />	<link rel="stylesheet" type="text/css" href="/stylesheets/home.css" />	</head>
	<link rel="stylesheet" href="/stylesheets/basic.css" type="text/css">
   	<script type='text/javascript' src='/js/jquery.js'></script>
	<script type='text/javascript' src='/js/jquery-1.7.2.min.js'></script>
	<body>
		<div class="container">
			<div id="header" class="span12">
				<h1>Seedr</h1>
			</div>
			<div class="span12">
				<h3>Listing rss_sources</h3>

				<table>
				  <tr>
				    <th>Source URL</th>
				    <th></th>
				    <th></th>
				    <th></th>
				  </tr>
				
				<% @rss_sources.each do |rss_source| %>
				  <tr>
				    <td><%= rss_source.source_url %></td>
				    <td><%= link_to 'Edit', edit_rss_source_path(rss_source), :class=>'btn btn-info' %></td>
				    <td><%= link_to 'Destroy', rss_source, :confirm => 'Are you sure?', :method => :delete, :class=>'btn btn-danger'  %></td>
				  </tr>
				<% end %>
				</table>

				<br />
				
				<%= link_to 'New RSS source', new_rss_source_path, :class=>'btn btn-info' %>
				
			</div>
			<div class='span12' id='footer' style="margin-top: 120px">
				<div class='row'>
					<div class='span3'>
						<ul class="nav nav-pills">
							<div>
							<a href="https://twitter.com/SeedrSocial" class="twitter-follow-button" data-show-count="false">Follow @SeedrSocial</a>
							</div>	
							<div class="fb-like" data-href="http://www.facebook.com/SeedrSocial" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
												
						</ul>
					</div>
					<div class='span8' id='copyright'><p>Contact us at contact@seedrsocial.com | &copy;2012 Seedr. All rights reserved.</p></div>
				</div>
			</div>
		</div> <!--container!-->
		<div id="fb-root"></div>
		
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=386595491374845";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<!-- <script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script> -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script></body>
</html>

app/views/rss_sources/new.html.erb
<%= render 'form' %>

app/views/rss_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rss_source.user_id %>
</p>

<p>
  <b>Source url:</b>
  <%= @rss_source.source_url %>
</p>


<%= link_to 'Edit', edit_rss_source_path(@rss_source) %> |
<%= link_to 'Back', rss_sources_path %>