config/routes.rb
Bigdata::Application.routes.draw do
  resources :tweets_weights

  resources :suggested_keywords
    
  get "getstarted/twitter"

  get "getstarted/topic"

  get "getstarted/welcome"
  
  get "getstartedtwitter/new"
  get "getstartedtwitter/callback"
  resources :friends_withs

  resources :rss_sources

  resources :comments

  resources :twitter_accounts

  get "analytics/index"

  get "settings/index"

  post "twitter_accounts/new"
  get "twitter_accounts/new"
  resources :search_bins
  get "search_bins/new"

  get "search_bins/create"

  post "search_bins/new"

resource :twitter_account
  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback

  resources :users

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  post "sessions/new"
    
    post "sessions/create"

  get "admin/index"

  get "twitter_manager/post"
   
  resources :l_tweets

  get "reader/index"
  post "reader/update_news"
  get  "reader/update_news"
  get "reader/setting"

  get "reader/analytics"

  resources :landing_page	
	
  get "landing_page/index"
	
  resources :visitors
  
  get 'admin' => 'reader#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "aboutus/about"
  get "register/reg"
  get "home/index"
  get "home/register"
  get "home/about"
  resources :cohorts
  resources :prospective_users
  get "prospective_users/new"

  root :to => 'landing_page#index'

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_filter :authenticate
  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @visitors }
    end
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @visitor }
    end
  end

  # GET /visitors/new
  # GET /visitors/new.json
  def new
    @visitor = Visitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @visitor }
    end
  end

  # GET /visitors/1/edit
  def edit
    @visitor = Visitor.find(params[:id])
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(params[:visitor])

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, :notice => 'Visitor was successfully created.' }
        format.json { render :json => @visitor, :status => :created, :location => @visitor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @visitor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /visitors/1
  # PUT /visitors/1.json
  def update
    @visitor = Visitor.find(params[:id])

    respond_to do |format|
      if @visitor.update_attributes(params[:visitor])
        format.html { redirect_to @visitor, :notice => 'Visitor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @visitor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor = Visitor.find(params[:id])
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url }
      format.json { head :ok }
    end
  end

protected

def authenticate
  authenticate_or_request_with_http_basic do |username, password|
    username == "admin" && password == "bigdata"
  end
end

end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_for(@visitor) do |f| %>
  <% if @visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% @visitor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :browser %><br />
    <%= f.text_field :browser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing visitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<h1>Listing visitors</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Ip</th>
    <th>Browser</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visitors.each do |visitor| %>
  <tr>
    <td><%= visitor.id %></td>
    <td><%= visitor.IP %></td>
    <td><%= visitor.browser %></td>
    <td><%= link_to 'Show', visitor %></td>
    <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
    <td><%= link_to 'Destroy', visitor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<h1>New visitor</h1>

<%= render 'form' %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @visitor.id %>
</p>

<p>
  <b>Ip:</b>
  <%= @visitor.ip %>
</p>

<p>
  <b>Browser:</b>
  <%= @visitor.browser %>
</p>


<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>