config/routes.rb
Bigdata::Application.routes.draw do
  resources :tweets_weights

  resources :suggested_keywords
    
  get "getstarted/twitter"

  get "getstarted/topic"

  get "getstarted/welcome"
  
  get "getstartedtwitter/new"
  get "getstartedtwitter/callback"
  resources :friends_withs

  resources :rss_sources

  resources :comments

  resources :twitter_accounts

  get "analytics/index"

  get "settings/index"

  post "twitter_accounts/new"
  get "twitter_accounts/new"
  resources :search_bins
  get "search_bins/new"

  get "search_bins/create"

  post "search_bins/new"

resource :twitter_account
  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback

  resources :users

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  post "sessions/new"
    
    post "sessions/create"

  get "admin/index"

  get "twitter_manager/post"
   
  resources :l_tweets

  get "reader/index"
  post "reader/update_news"
  get  "reader/update_news"
  get "reader/setting"

  get "reader/analytics"

  resources :landing_page	
	
  get "landing_page/index"
	
  resources :visitors
  
  get 'admin' => 'reader#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "aboutus/about"
  get "register/reg"
  get "home/index"
  get "home/register"
  get "home/about"
  resources :cohorts
  resources :prospective_users
  get "prospective_users/new"

  root :to => 'landing_page#index'

end

app/models/suggested_keyword.rb
class SuggestedKeyword < ActiveRecord::Base
end

app/controllers/suggested_keywords_controller.rb
class SuggestedKeywordsController < ApplicationController
  # GET /suggested_keywords
  # GET /suggested_keywords.json
  def index
    @suggested_keywords = SuggestedKeyword.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @suggested_keywords }
    end
  end

  # GET /suggested_keywords/1
  # GET /suggested_keywords/1.json
  def show
    @suggested_keyword = SuggestedKeyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @suggested_keyword }
    end
  end

  # GET /suggested_keywords/new
  # GET /suggested_keywords/new.json
  def new
    @suggested_keyword = SuggestedKeyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @suggested_keyword }
    end
  end

  # GET /suggested_keywords/1/edit
  def edit
    @suggested_keyword = SuggestedKeyword.find(params[:id])
  end

  # POST /suggested_keywords
  # POST /suggested_keywords.json
  def create
    @suggested_keyword = SuggestedKeyword.new(params[:suggested_keyword])

    respond_to do |format|
      if @suggested_keyword.save
        format.html { redirect_to @suggested_keyword, :notice => 'Suggested keyword was successfully created.' }
        format.json { render :json => @suggested_keyword, :status => :created, :location => @suggested_keyword }
      else
        format.html { render :action => "new" }
        format.json { render :json => @suggested_keyword.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /suggested_keywords/1
  # PUT /suggested_keywords/1.json
  def update
    @suggested_keyword = SuggestedKeyword.find(params[:id])

    respond_to do |format|
      if @suggested_keyword.update_attributes(params[:suggested_keyword])
        format.html { redirect_to @suggested_keyword, :notice => 'Suggested keyword was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @suggested_keyword.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /suggested_keywords/1
  # DELETE /suggested_keywords/1.json
  def destroy
    @suggested_keyword = SuggestedKeyword.find(params[:id])
    @suggested_keyword.destroy

    respond_to do |format|
      format.html { redirect_to suggested_keywords_url }
      format.json { head :ok }
    end
  end
end

app/helpers/suggested_keywords_helper.rb
module SuggestedKeywordsHelper
end

app/views/suggested_keywords/_form.html.erb
<%= form_for(@suggested_keyword) do |f| %>
  <% if @suggested_keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggested_keyword.errors.count, "error") %> prohibited this suggested_keyword from being saved:</h2>

      <ul>
      <% @suggested_keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggested_keywords/edit.html.erb
<h1>Editing suggested_keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggested_keyword %> |
<%= link_to 'Back', suggested_keywords_path %>

app/views/suggested_keywords/index.html.erb
<h1>Listing suggested_keywords</h1>

<table>
  <tr>
    <th>User</th>
    <th>Keyword</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suggested_keywords.each do |suggested_keyword| %>
  <tr>
    <td><%= suggested_keyword.user_id %></td>
    <td><%= suggested_keyword.keyword %></td>
    <td><%= suggested_keyword.weight %></td>
    <td><%= link_to 'Show', suggested_keyword %></td>
    <td><%= link_to 'Edit', edit_suggested_keyword_path(suggested_keyword) %></td>
    <td><%= link_to 'Destroy', suggested_keyword, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Suggested keyword', new_suggested_keyword_path %>

app/views/suggested_keywords/new.html.erb
<h1>New suggested_keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', suggested_keywords_path %>

app/views/suggested_keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @suggested_keyword.user_id %>
</p>

<p>
  <b>Keyword:</b>
  <%= @suggested_keyword.keyword %>
</p>

<p>
  <b>Weight:</b>
  <%= @suggested_keyword.weight %>
</p>


<%= link_to 'Edit', edit_suggested_keyword_path(@suggested_keyword) %> |
<%= link_to 'Back', suggested_keywords_path %>