config/routes.rb
Bigdata::Application.routes.draw do
  resources :tweets_weights

  resources :suggested_keywords
    
  get "getstarted/twitter"

  get "getstarted/topic"

  get "getstarted/welcome"
  
  get "getstartedtwitter/new"
  get "getstartedtwitter/callback"
  resources :friends_withs

  resources :rss_sources

  resources :comments

  resources :twitter_accounts

  get "analytics/index"

  get "settings/index"

  post "twitter_accounts/new"
  get "twitter_accounts/new"
  resources :search_bins
  get "search_bins/new"

  get "search_bins/create"

  post "search_bins/new"

resource :twitter_account
  match '/callback/twitter/' => "twitter_accounts#callback", :as => :twitter_callback

  resources :users

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  post "sessions/new"
    
    post "sessions/create"

  get "admin/index"

  get "twitter_manager/post"
   
  resources :l_tweets

  get "reader/index"
  post "reader/update_news"
  get  "reader/update_news"
  get "reader/setting"

  get "reader/analytics"

  resources :landing_page	
	
  get "landing_page/index"
	
  resources :visitors
  
  get 'admin' => 'reader#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "aboutus/about"
  get "register/reg"
  get "home/index"
  get "home/register"
  get "home/about"
  resources :cohorts
  resources :prospective_users
  get "prospective_users/new"

  root :to => 'landing_page#index'

end

app/models/prospective_user.rb
class ProspectiveUser < ActiveRecord::Base
end

app/controllers/prospective_users_controller.rb
class ProspectiveUsersController < ApplicationController
  skip_before_filter :authorize
  before_filter :authenticate , :only => [ :edit, :delete, :index]

  # GET /prospective_users
  # GET /prospective_users.json
  def index
    @prospective_users = ProspectiveUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @prospective_users }
    end
  end

  # GET /prospective_users/1
  # GET /prospective_users/1.json
  def show
    @prospective_user = ProspectiveUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @prospective_user }
    end
  end

  # GET /prospective_users/new
  # GET /prospective_users/new.json
  def new
    @prospective_user = ProspectiveUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @prospective_user }
    end
  end

  # GET /prospective_users/1/edit
  def edit
    @prospective_user = ProspectiveUser.find(params[:id])
  end

  # POST /prospective_users
  # POST /prospective_users.json
  def create
        @prospective_user = ProspectiveUser.new(params[:prospective_user])
    # @prospective_user.fname = params[:fname]
    # @prospective_user.lname = params[:lname]
    #@prospective_user.email = params[:email]
    #@prospective_user.comment = params[:comment]
    @prospective_user.created_at = Time.now
    @prospective_user.updated_at = Time.now
    respond_to do |format|
      if @prospective_user.save
        format.html { redirect_to "/", :notice => 'Prospective user was successfully created.' }
        format.json { render :json => @prospective_user, :status => :created, :location => @prospective_user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @prospective_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /prospective_users/1
  # PUT /prospective_users/1.json
  def update
    @prospective_user = ProspectiveUser.find(params[:id])

    respond_to do |format|
      if @prospective_user.update_attributes(params[:prospective_user])
        format.html { redirect_to @prospective_user, :notice => 'Prospective user was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @prospective_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /prospective_users/1
  # DELETE /prospective_users/1.json
  def destroy
    @prospective_user = ProspectiveUser.find(params[:id])
    @prospective_user.destroy

    respond_to do |format|
      format.html { redirect_to prospective_users_url }
      format.json { head :ok }
    end
  end

protected

def authenticate
  authenticate_or_request_with_http_basic do |username, password|
    username == "admin" && password == "bigdata"
  end
end
end 

app/helpers/prospective_users_helper.rb
module ProspectiveUsersHelper
end

app/views/prospective_users/_form.html.erb
<%= form_for(@prospective_user) do |f| %>
  <% if @prospective_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospective_user.errors.count, "error") %> prohibited this prospective_user from being saved:</h2>

      <ul>
      <% @prospective_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospective_users/edit.html.erb
<h1>Editing prospective_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospective_user %> |
<%= link_to 'Back', prospective_users_path %>

app/views/prospective_users/index.html.erb
<h1>Listing prospective_users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prospective_users.each do |prospective_user| %>
  <tr>
    <td><%= prospective_user.email %></td>
    <td><%= prospective_user.comment %></td>
    <td><%= link_to 'Show', prospective_user %></td>
    <td><%= link_to 'Edit', edit_prospective_user_path(prospective_user) %></td>
    <td><%= link_to 'Destroy', prospective_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prospective user', new_prospective_user_path %>

app/views/prospective_users/new.html.erb
<h1>New prospective_user</h1>

<%= render 'form' %>

<%= link_to 'Back', prospective_users_path %>

app/views/prospective_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @prospective_user.email %>
</p>

<p>
  <b>Comment:</b>
  <%= @prospective_user.comment %>
</p>


<%= link_to 'Edit', edit_prospective_user_path(@prospective_user) %> |
<%= link_to 'Back', prospective_users_path %>